### ISSUE TITLE
countdown timer

### ISSUE THREAD

**Issue by jjj092353** [earthcoinproject/earthcoin#9]
since this link no longer works:
http://poolerino.com/eaccountdown/

can I volunteer my pool eac.lifeforce.info to provide this information if you supply me with the code to calculate/display it?

thanks

**Comment by linki** [comment]
closing as lifeforce doesn't exist anymore.

**Comment by linki** [comment]
A working coundown timer would be nice, though.

**Comment by jjj092353** [comment]
Lifeforce was replaced by smarterhash and I could do it there

**Comment by linki** [comment]
thx for the update. i'll get in touch with you next week.
